FROM ubuntu:24.04

RUN apt update && apt install -y openssh-server python3 sudo nginx

RUN useradd -ms /bin/bash ansible && echo 'ansible:ansible' | chpasswd && adduser ansible sudo

RUN mkdir /var/run/sshd

COPY ./site /var/www/html

EXPOSE 22 80

CMD service nginx start && /usr/sbin/sshd -D
